tasks:
  - name: Bootstrap with Poetry
    before: |
      export POETRY_VIRTUALENVS_IN_PROJECT=true
    init: |
      PY_VERS=$(cat /workspace/ecr-registry-refresh/.python-version)
      pyenv install $PY_VERS
      pyenv local $PY_VERS
      curl -sSL https://install.python-poetry.org | python3 -
      /home/gitpod/.local/bin/poetry install
    command: |
      . /workspace/ecr-registry-refresh/.venv/bin/activate

vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod