---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gitpod
  name: ecr-helper-access-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["regcred"]
  verbs: ["patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: health-check-role-binding
  namespace: gitpod
subjects:
- kind: ServiceAccount
  name: sa-health-check
  namespace: health-check
  apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-secrets
  apiGroup: ""
